# Site settings
title: Community Assessment and Data Analysis
email: patilv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an initiative of Gonzaga University's School of Business Administration.
baseurl: # the subpath of your site, e.g. /blog/
url: https://gonzagasbacada.github.io  # the base hostname & protocol for your site
#twitter_username: twitter_username
github_username:  gonzagasbacada

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"
gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]


#collections:
#  portfolio:
#    output: true
#    permalink: /portfolio/:path/
#  poetry:
#    output: true
#    permalink: /poetry/:path/


